// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdqn_fpgatop.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDqn_fpgatop_CfgInitialize(XDqn_fpgatop *InstancePtr, XDqn_fpgatop_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDqn_fpgatop_Start(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL) & 0x80;
    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDqn_fpgatop_IsDone(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDqn_fpgatop_IsIdle(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDqn_fpgatop_IsReady(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDqn_fpgatop_EnableAutoRestart(XDqn_fpgatop *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XDqn_fpgatop_DisableAutoRestart(XDqn_fpgatop *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL, 0);
}

void XDqn_fpgatop_Set_ex_memory(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_EX_MEMORY_DATA, Data);
}

u32 XDqn_fpgatop_Get_ex_memory(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_EX_MEMORY_DATA);
    return Data;
}

void XDqn_fpgatop_Set_vector_in(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_VECTOR_IN_DATA, Data);
}

u32 XDqn_fpgatop_Get_vector_in(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_VECTOR_IN_DATA);
    return Data;
}

void XDqn_fpgatop_Set_matrix_in(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_MATRIX_IN_DATA, Data);
}

u32 XDqn_fpgatop_Get_matrix_in(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_MATRIX_IN_DATA);
    return Data;
}

void XDqn_fpgatop_Set_bias_in(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_BIAS_IN_DATA, Data);
}

u32 XDqn_fpgatop_Get_bias_in(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_BIAS_IN_DATA);
    return Data;
}

void XDqn_fpgatop_Set_result(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_RESULT_DATA, Data);
}

u32 XDqn_fpgatop_Get_result(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_RESULT_DATA);
    return Data;
}

void XDqn_fpgatop_Set_info_learning_rate(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_LEARNING_RATE_DATA, Data);
}

u32 XDqn_fpgatop_Get_info_learning_rate(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_LEARNING_RATE_DATA);
    return Data;
}

void XDqn_fpgatop_Set_info_reward_decay(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_REWARD_DECAY_DATA, Data);
}

u32 XDqn_fpgatop_Get_info_reward_decay(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_REWARD_DECAY_DATA);
    return Data;
}

void XDqn_fpgatop_Set_info_iter_n(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_ITER_N_DATA, Data);
}

u32 XDqn_fpgatop_Get_info_iter_n(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_ITER_N_DATA);
    return Data;
}

void XDqn_fpgatop_Set_info_batch_size(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_BATCH_SIZE_DATA, Data);
}

u32 XDqn_fpgatop_Get_info_batch_size(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_BATCH_SIZE_DATA);
    return Data;
}

void XDqn_fpgatop_Set_info_replace(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_REPLACE_DATA, Data);
}

u32 XDqn_fpgatop_Get_info_replace(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_INFO_REPLACE_DATA);
    return Data;
}

void XDqn_fpgatop_Set_doInit(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_DOINIT_DATA, Data);
}

u32 XDqn_fpgatop_Get_doInit(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_DOINIT_DATA);
    return Data;
}

void XDqn_fpgatop_Set_mode(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_MODE_DATA, Data);
}

u32 XDqn_fpgatop_Get_mode(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_MODE_DATA);
    return Data;
}

void XDqn_fpgatop_Set_check(XDqn_fpgatop *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_CHECK_DATA, Data);
}

u32 XDqn_fpgatop_Get_check(XDqn_fpgatop *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_CHECK_DATA);
    return Data;
}

void XDqn_fpgatop_InterruptGlobalEnable(XDqn_fpgatop *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_GIE, 1);
}

void XDqn_fpgatop_InterruptGlobalDisable(XDqn_fpgatop *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_GIE, 0);
}

void XDqn_fpgatop_InterruptEnable(XDqn_fpgatop *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_IER);
    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_IER, Register | Mask);
}

void XDqn_fpgatop_InterruptDisable(XDqn_fpgatop *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_IER);
    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_IER, Register & (~Mask));
}

void XDqn_fpgatop_InterruptClear(XDqn_fpgatop *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDqn_fpgatop_WriteReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_ISR, Mask);
}

u32 XDqn_fpgatop_InterruptGetEnabled(XDqn_fpgatop *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_IER);
}

u32 XDqn_fpgatop_InterruptGetStatus(XDqn_fpgatop *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDqn_fpgatop_ReadReg(InstancePtr->Control_BaseAddress, XDQN_FPGATOP_CONTROL_ADDR_ISR);
}

