// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDQN_FPGATOP_H
#define XDQN_FPGATOP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdqn_fpgatop_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XDqn_fpgatop_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XDqn_fpgatop;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDqn_fpgatop_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDqn_fpgatop_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDqn_fpgatop_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDqn_fpgatop_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDqn_fpgatop_Initialize(XDqn_fpgatop *InstancePtr, u16 DeviceId);
XDqn_fpgatop_Config* XDqn_fpgatop_LookupConfig(u16 DeviceId);
int XDqn_fpgatop_CfgInitialize(XDqn_fpgatop *InstancePtr, XDqn_fpgatop_Config *ConfigPtr);
#else
int XDqn_fpgatop_Initialize(XDqn_fpgatop *InstancePtr, const char* InstanceName);
int XDqn_fpgatop_Release(XDqn_fpgatop *InstancePtr);
#endif

void XDqn_fpgatop_Start(XDqn_fpgatop *InstancePtr);
u32 XDqn_fpgatop_IsDone(XDqn_fpgatop *InstancePtr);
u32 XDqn_fpgatop_IsIdle(XDqn_fpgatop *InstancePtr);
u32 XDqn_fpgatop_IsReady(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_EnableAutoRestart(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_DisableAutoRestart(XDqn_fpgatop *InstancePtr);

void XDqn_fpgatop_Set_ex_memory(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_ex_memory(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_vector_in(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_vector_in(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_matrix_in(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_matrix_in(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_bias_in(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_bias_in(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_result(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_result(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_info_learning_rate(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_info_learning_rate(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_info_reward_decay(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_info_reward_decay(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_info_iter_n(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_info_iter_n(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_info_batch_size(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_info_batch_size(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_info_replace(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_info_replace(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_doInit(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_doInit(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_mode(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_mode(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_Set_check(XDqn_fpgatop *InstancePtr, u32 Data);
u32 XDqn_fpgatop_Get_check(XDqn_fpgatop *InstancePtr);

void XDqn_fpgatop_InterruptGlobalEnable(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_InterruptGlobalDisable(XDqn_fpgatop *InstancePtr);
void XDqn_fpgatop_InterruptEnable(XDqn_fpgatop *InstancePtr, u32 Mask);
void XDqn_fpgatop_InterruptDisable(XDqn_fpgatop *InstancePtr, u32 Mask);
void XDqn_fpgatop_InterruptClear(XDqn_fpgatop *InstancePtr, u32 Mask);
u32 XDqn_fpgatop_InterruptGetEnabled(XDqn_fpgatop *InstancePtr);
u32 XDqn_fpgatop_InterruptGetStatus(XDqn_fpgatop *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
