// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdqn_fpgatop.h"

extern XDqn_fpgatop_Config XDqn_fpgatop_ConfigTable[];

XDqn_fpgatop_Config *XDqn_fpgatop_LookupConfig(u16 DeviceId) {
	XDqn_fpgatop_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDQN_FPGATOP_NUM_INSTANCES; Index++) {
		if (XDqn_fpgatop_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDqn_fpgatop_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDqn_fpgatop_Initialize(XDqn_fpgatop *InstancePtr, u16 DeviceId) {
	XDqn_fpgatop_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDqn_fpgatop_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDqn_fpgatop_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

