// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ex_memory
//        bit 31~0 - ex_memory[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of vector_in
//        bit 31~0 - vector_in[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of matrix_in
//        bit 31~0 - matrix_in[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of bias_in
//        bit 31~0 - bias_in[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of result
//        bit 31~0 - result[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of info_learning_rate
//        bit 31~0 - info_learning_rate[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of info_reward_decay
//        bit 31~0 - info_reward_decay[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of info_iter_n
//        bit 31~0 - info_iter_n[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of info_batch_size
//        bit 31~0 - info_batch_size[31:0] (Read/Write)
// 0x54 : reserved
// 0x58 : Data signal of info_replace
//        bit 0  - info_replace[0] (Read/Write)
//        others - reserved
// 0x5c : reserved
// 0x60 : Data signal of doInit
//        bit 0  - doInit[0] (Read/Write)
//        others - reserved
// 0x64 : reserved
// 0x68 : Data signal of mode
//        bit 0  - mode[0] (Read/Write)
//        others - reserved
// 0x6c : reserved
// 0x70 : Data signal of check
//        bit 0  - check[0] (Read/Write)
//        others - reserved
// 0x74 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDQN_FPGATOP_CONTROL_ADDR_AP_CTRL                 0x00
#define XDQN_FPGATOP_CONTROL_ADDR_GIE                     0x04
#define XDQN_FPGATOP_CONTROL_ADDR_IER                     0x08
#define XDQN_FPGATOP_CONTROL_ADDR_ISR                     0x0c
#define XDQN_FPGATOP_CONTROL_ADDR_EX_MEMORY_DATA          0x10
#define XDQN_FPGATOP_CONTROL_BITS_EX_MEMORY_DATA          32
#define XDQN_FPGATOP_CONTROL_ADDR_VECTOR_IN_DATA          0x18
#define XDQN_FPGATOP_CONTROL_BITS_VECTOR_IN_DATA          32
#define XDQN_FPGATOP_CONTROL_ADDR_MATRIX_IN_DATA          0x20
#define XDQN_FPGATOP_CONTROL_BITS_MATRIX_IN_DATA          32
#define XDQN_FPGATOP_CONTROL_ADDR_BIAS_IN_DATA            0x28
#define XDQN_FPGATOP_CONTROL_BITS_BIAS_IN_DATA            32
#define XDQN_FPGATOP_CONTROL_ADDR_RESULT_DATA             0x30
#define XDQN_FPGATOP_CONTROL_BITS_RESULT_DATA             32
#define XDQN_FPGATOP_CONTROL_ADDR_INFO_LEARNING_RATE_DATA 0x38
#define XDQN_FPGATOP_CONTROL_BITS_INFO_LEARNING_RATE_DATA 32
#define XDQN_FPGATOP_CONTROL_ADDR_INFO_REWARD_DECAY_DATA  0x40
#define XDQN_FPGATOP_CONTROL_BITS_INFO_REWARD_DECAY_DATA  32
#define XDQN_FPGATOP_CONTROL_ADDR_INFO_ITER_N_DATA        0x48
#define XDQN_FPGATOP_CONTROL_BITS_INFO_ITER_N_DATA        32
#define XDQN_FPGATOP_CONTROL_ADDR_INFO_BATCH_SIZE_DATA    0x50
#define XDQN_FPGATOP_CONTROL_BITS_INFO_BATCH_SIZE_DATA    32
#define XDQN_FPGATOP_CONTROL_ADDR_INFO_REPLACE_DATA       0x58
#define XDQN_FPGATOP_CONTROL_BITS_INFO_REPLACE_DATA       1
#define XDQN_FPGATOP_CONTROL_ADDR_DOINIT_DATA             0x60
#define XDQN_FPGATOP_CONTROL_BITS_DOINIT_DATA             1
#define XDQN_FPGATOP_CONTROL_ADDR_MODE_DATA               0x68
#define XDQN_FPGATOP_CONTROL_BITS_MODE_DATA               1
#define XDQN_FPGATOP_CONTROL_ADDR_CHECK_DATA              0x70
#define XDQN_FPGATOP_CONTROL_BITS_CHECK_DATA              1

